# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SinkerCalculation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '12.0'
  # Pods for EurekaSample
  pod 'Eureka', '~>5.3.3'

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
end
